const app=document.querySelector('#app'),toast=document.querySelector('#toast'),symbols=['▲','◆','●','■'];
const S={role:null,code:null,peer:null,host:null,connections:new Map,players:new Map,questions:[],selected:[],current:-1,phase:'home',answers:new Map,startedAt:0,timerId:null,questionTimer:null,question:null};
const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML},norm=v=>String(v??'').trim().replace(/\s+/g,' ').toLocaleLowerCase('he-IL');
function notify(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function render(h){clearInterval(S.timerId);app.innerHTML=h}function panel(c,w=false){return `<section class="panel ${w?'wide':''}">${c}</section>`}
const peerId=c=>`family-live-quiz-${c}`,send=(c,type,payload={})=>c?.open&&c.send({type,payload}),broadcast=(t,p={})=>S.connections.forEach(c=>send(c,t,p));
const board=()=>[...S.players.values()].map(({id,name,score})=>({id,name,score})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'he'));
function closeNetwork(){clearTimeout(S.questionTimer);S.peer?.destroy();S.peer=null;S.host=null;S.connections.clear();S.players.clear()}
function home(){closeNetwork();S.role=null;S.phase='home';render(panel(`<h1>מי מכיר את המשפחה הכי טוב?</h1><p>חידון יום הולדת חי, צבעוני ומהיר. בחרו כיצד להיכנס.</p><div class="actions"><button class="btn" id="hostBtn">🎙️ פתיחת משחק כמנחה</button><button class="btn secondary" id="playerBtn">📱 הצטרפות כשחקן</button></div>`));hostBtn.onclick=hostSetup;playerBtn.onclick=playerJoin}
async function hostSetup(){S.role='host';if(!S.questions.length)try{S.questions=await fetch('questions.json').then(r=>{if(!r.ok)throw Error();return r.json()})}catch{return notify('לא ניתן לטעון את מאגר השאלות')}render(panel(`<h2>הגדרת המשחק</h2><div class="field"><label for="count">כמה שאלות לשחק?</label><select id="count" class="select">${[2,3,4,5,6].filter(n=>n<=S.questions.length).map(n=>`<option value="${n}">${n} שאלות</option>`).join('')}</select></div><div class="actions"><button class="btn" id="createBtn">יצירת משחק</button><button class="btn secondary" id="backBtn">חזרה</button></div>`));backBtn.onclick=home;createBtn.onclick=()=>createHost(+count.value)}
function createHost(count,attempt=0){if(attempt>4)return notify('לא ניתן ליצור קוד. נסו שוב.');S.code=String(Math.floor(100000+Math.random()*900000));S.selected=[...S.questions].sort(()=>Math.random()-.5).slice(0,count);S.current=-1;S.phase='lobby';S.players.clear();S.connections.clear();S.peer=new Peer(peerId(S.code));S.peer.on('open',hostLobby);S.peer.on('connection',c=>{c.on('data',m=>hostMessage(c,m));c.on('close',()=>removePlayer(c.peer));c.on('error',()=>removePlayer(c.peer))});S.peer.on('error',e=>{if(e.type==='unavailable-id'){S.peer.destroy();createHost(count,attempt+1)}else notify('שגיאת חיבור. בדקו שיש אינטרנט ונסו שוב.')})}
function hostMessage(c,m){if(m?.type==='join'){const name=String(m.payload?.name||'').trim().slice(0,24);if(S.phase!=='lobby')return send(c,'join-error',{error:'המשחק כבר התחיל'});if(!name)return send(c,'join-error',{error:'צריך להזין שם'});if([...S.players.values()].some(p=>norm(p.name)===norm(name)))return send(c,'join-error',{error:'השם הזה כבר תפוס'});S.connections.set(c.peer,c);S.players.set(c.peer,{id:c.peer,name,score:0});send(c,'joined',{player:{name,score:0}});hostLobby()}if(m?.type==='answer')receiveAnswer(c.peer,m.payload?.answer)}
function removePlayer(id){S.connections.delete(id);if(S.phase==='lobby'){S.players.delete(id);hostLobby()}}
function hostLobby(){const ps=[...S.players.values()];render(panel(`<p>פתחו בטלפונים את האתר הזה ובחרו ״הצטרפות״</p><h2>קוד המשחק</h2><div class="code">${S.code}</div><div class="players">${ps.map(p=>`<span class="chip">${esc(p.name)}</span>`).join('')}</div><p>${ps.length?`${ps.length} שחקנים מחכים`:'ממתינים לשחקנים…'}</p><button class="btn green" id="startBtn" ${ps.length?'':'disabled'}>🚀 מתחילים!</button>`));startBtn.onclick=startNext}
function playerJoin(){S.role='player';render(panel(`<h2>מצטרפים למשחק</h2><form id="joinForm"><div class="field"><label for="gameCode">קוד בן 6 ספרות</label><input id="gameCode" class="input" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></div><div class="field"><label for="playerName">השם שלך</label><input id="playerName" class="input" maxlength="24" required></div><button class="btn" id="joinBtn">כניסה למשחק</button></form><div class="actions"><button class="btn secondary" id="backBtn">חזרה</button></div>`));backBtn.onclick=home;joinForm.onsubmit=e=>{e.preventDefault();connectPlayer(gameCode.value.trim(),playerName.value.trim())}}
function connectPlayer(code,name){joinBtn.disabled=true;joinBtn.textContent='מתחברים…';S.code=code;S.peer=new Peer;S.peer.on('open',()=>{const c=S.peer.connect(peerId(code),{reliable:true});S.host=c;c.on('open',()=>send(c,'join',{name}));c.on('data',playerMessage);c.on('close',gameClosed);c.on('error',()=>joinFailed('החיבור למנחה נכשל'));setTimeout(()=>{if(!c.open)joinFailed('קוד המשחק לא נמצא')},8000)});S.peer.on('error',()=>joinFailed('החיבור נכשל. בדקו את הקוד והאינטרנט.'))}
function joinFailed(m){S.peer?.destroy();S.peer=null;notify(m);setTimeout(playerJoin,500)}
function playerMessage({type,payload}={}){if(type==='join-error')joinFailed(payload.error);if(type==='joined'){S.phase='lobby';render(panel(`<div class="feedback-icon">🙌</div><h2>נכנסת למשחק!</h2><p>מחכים שהמנחה יתחיל…</p><span class="chip">${esc(payload.player.name)}</span>`))}if(type==='question')questionScreen(payload);if(type==='results')playerResults(payload.result);if(type==='finished')finish(payload.leaderboard);if(type==='closed')gameClosed()}
function startNext(){S.current++;S.phase='question';S.answers.clear();const q=S.selected[S.current];S.startedAt=Date.now();const {correctAnswer,...safe}=q,p={question:safe,questionNumber:S.current+1,totalQuestions:S.selected.length,startedAt:S.startedAt};broadcast('question',p);questionScreen(p);clearTimeout(S.questionTimer);S.questionTimer=setTimeout(endQuestion,q.timeLimit*1000)}
function questionScreen(p){S.phase='question';S.question=p.question;const q=p.question,media=q.mediaUrl?`<img class="media" src="${esc(q.mediaUrl)}" alt="מדיה לשאלה">`:'';const answers=q.type==='text-input'?`<form id="answerForm"><div class="field"><label for="textAnswer">התשובה שלך</label><input id="textAnswer" class="input" maxlength="80" required autofocus></div><button class="btn">שליחת תשובה</button></form>`:`<div class="answer-grid ${q.type==='boolean'?'boolean-grid':''}">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}"><span class="shape">${symbols[i]}</span>${esc(o)}</button>`).join('')}</div>`;render(panel(`<div class="meta"><span class="pill">שאלה ${p.questionNumber} מתוך ${p.totalQuestions}</span><div class="timer"><span id="seconds">${q.timeLimit}</span></div>${S.role==='host'?'<span class="pill" id="answerCount">0 ענו</span>':'<span></span>'}</div>${media}<h2>${esc(q.question)}</h2>${S.role==='host'?'<p>השחקנים עונים עכשיו בטלפונים…</p>':answers}`,true));if(S.role==='player')bindAnswers(q.type);startTimer(q.timeLimit,p.startedAt)}
function bindAnswers(type){if(type==='text-input')answerForm.onsubmit=e=>{e.preventDefault();submitAnswer(textAnswer.value)};else document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{document.querySelectorAll('.answer').forEach(x=>x.disabled=true);b.classList.add('selected');submitAnswer(+b.dataset.answer)})}
function submitAnswer(answer){send(S.host,'answer',{answer});render(panel(`<div class="feedback-icon">✓</div><h2>התשובה נקלטה!</h2><p>מחכים לסיום הזמן ולתוצאה…</p>`))}
function correct(q,a){if(q.type==='text-input'){const accepted=Array.isArray(q.correctAnswer)?q.correctAnswer:[q.correctAnswer];return accepted.some(x=>norm(x)===norm(a))}return +a===+q.correctAnswer}
function receiveAnswer(id,answer){if(S.phase!=='question'||S.answers.has(id)||!S.players.has(id))return;const q=S.selected[S.current],ok=correct(q,answer),remaining=Math.max(0,1-(Date.now()-S.startedAt)/(q.timeLimit*1000)),points=ok?Math.round(500+500*remaining):0,p=S.players.get(id);p.score+=points;S.answers.set(id,{answer,correct:ok,points,score:p.score});const el=document.querySelector('#answerCount');if(el)el.textContent=`${S.answers.size}/${S.players.size} ענו`;if(S.answers.size>=S.players.size)endQuestion()}
function endQuestion(){if(S.phase!=='question')return;clearTimeout(S.questionTimer);S.phase='results';const q=S.selected[S.current],distribution={};S.answers.forEach(a=>{const k=q.type==='text-input'?norm(a.answer)||'ללא תשובה':String(a.answer);distribution[k]=(distribution[k]||0)+1});S.connections.forEach((c,id)=>send(c,'results',{result:S.answers.get(id)||{correct:false,points:0,score:S.players.get(id)?.score||0}}));hostResults({correctAnswer:q.correctAnswer,distribution,leaderboard:board()})}
function playerResults(r){render(panel(`<div class="feedback-icon">${r.correct?'🎉':'💪'}</div><h2 class="${r.correct?'correct':'wrong'}">${r.correct?'תשובה נכונה!':'לא הפעם'}</h2><h1>+${r.points}</h1><p>הניקוד הכולל שלך: ${r.score}</p><p>ממתינים לשאלה הבאה…</p>`))}
function hostResults(d){const q=S.selected[S.current],answer=q.type==='text-input'?(Array.isArray(d.correctAnswer)?d.correctAnswer[0]:d.correctAnswer):q.options[d.correctAnswer],entries=Object.entries(d.distribution),max=Math.max(1,...entries.map(([,n])=>n)),bars=entries.length?entries.map(([k,n])=>{const label=q.type==='text-input'?k:q.options[+k]??k;return `<div class="bar-row"><b>${esc(label)}</b><div class="bar-track"><div class="bar-fill" style="width:${n/max*100}%"></div></div><span>${n}</span></div>`}).join(''):'<p>לא נשלחו תשובות</p>';render(panel(`<h2>התשובה הנכונה: <span class="correct">${esc(answer)}</span></h2><div class="bars">${bars}</div><h2>לוח מובילים</h2>${boardHtml(d.leaderboard)}<button class="btn" id="nextBtn">${S.current+1>=S.selected.length?'לתוצאות הסופיות 🏆':'לשאלה הבאה ←'}</button>`,true));nextBtn.onclick=()=>{if(S.current+1>=S.selected.length){const b=board();broadcast('finished',{leaderboard:b});finish(b)}else startNext()}}
function startTimer(limit,started){const tick=()=>{const left=Math.max(0,limit-(Date.now()-started)/1000),el=document.querySelector('.timer'),s=document.querySelector('#seconds');if(el)el.style.setProperty('--progress',`${left/limit*100}%`);if(s)s.textContent=Math.ceil(left)};tick();S.timerId=setInterval(tick,100)}
const boardHtml=l=>`<div class="leaderboard">${l.map((p,i)=>`<div class="leader-row"><b>${i+1}</b><span>${esc(p.name)}</span><strong>${p.score}</strong></div>`).join('')}</div>`;
function finish(b){S.phase='finished';render(panel(`<div class="feedback-icon">🏆</div><h1>יש לנו מנצחים!</h1>${boardHtml(b)}<button class="btn" id="newGameBtn">משחק חדש</button>`,true));newGameBtn.onclick=home}
function gameClosed(){if(['finished','home'].includes(S.phase))return;render(panel(`<h2>המשחק נסגר</h2><p>החיבור למנחה הסתיים.</p><button class="btn" id="homeBtn">חזרה להתחלה</button>`));homeBtn.onclick=home}
window.addEventListener('beforeunload',()=>S.role==='host'&&broadcast('closed'));home();
